"""v0.1.0_initial_creation

Revision ID: 4bcb127a9622
Revises:
Create Date: 2025-09-13 12:50:00.961032

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bcb127a9622"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxonomy",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column("taxonomy_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), server_default="system", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["taxonomy_id"], ["taxonomy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_index(op.f("ix_taxonomy_taxonomy_id"), "taxonomy", ["taxonomy_id"], unique=False)
    op.create_index(op.f("ix_taxonomy_uuid"), "taxonomy", ["uuid"], unique=False)
    op.create_table(
        "video",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=512), nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("extension", sa.String(length=6), nullable=False),
        sa.Column("frames", sa.Integer(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("frame_rate", sa.Float(), nullable=True),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column(
            "status", sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="videostatus"), nullable=False
        ),
        sa.Column("status_message", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), server_default="system", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_video_uuid"), "video", ["uuid"], unique=False)
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("alias", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("taxonomy_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), server_default="system", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["taxonomy_id"], ["taxonomy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_taxonomy_id"), "entity", ["taxonomy_id"], unique=False)
    op.create_index(op.f("ix_entity_uuid"), "entity", ["uuid"], unique=True)
    op.create_table(
        "entity_media_gallery",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), server_default="system", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "path"),
    )
    op.create_index(op.f("ix_entity_media_gallery_entity_id"), "entity_media_gallery", ["entity_id"], unique=False)
    op.create_index(op.f("ix_entity_media_gallery_uuid"), "entity_media_gallery", ["uuid"], unique=True)
    op.create_table(
        "segment_detection",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("taxonomy_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), server_default="system", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["taxonomy_id"], ["taxonomy.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["video.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_segment_detection_entity_id"), "segment_detection", ["entity_id"], unique=False)
    op.create_index(op.f("ix_segment_detection_taxonomy_id"), "segment_detection", ["taxonomy_id"], unique=False)
    op.create_index(op.f("ix_segment_detection_uuid"), "segment_detection", ["uuid"], unique=True)
    op.create_index(op.f("ix_segment_detection_video_id"), "segment_detection", ["video_id"], unique=False)
    op.create_table(
        "detection",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=40), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("frame", sa.Integer(), nullable=False),
        sa.Column("segment_detection_id", sa.Integer(), nullable=False),
        sa.Column("detection_score", sa.Float(), nullable=False),
        sa.Column("entity_score", sa.Float(), nullable=False),
        sa.Column("bbox_x_min", sa.Float(), nullable=False),
        sa.Column("bbox_y_min", sa.Float(), nullable=False),
        sa.Column("bbox_x_max", sa.Float(), nullable=False),
        sa.Column("bbox_y_max", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.String(length=255), server_default="system", nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["segment_detection_id"], ["segment_detection.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["video.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detection_segment_detection_id"), "detection", ["segment_detection_id"], unique=False)
    op.create_index(op.f("ix_detection_uuid"), "detection", ["uuid"], unique=True)
    op.create_index(op.f("ix_detection_video_id"), "detection", ["video_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detection_video_id"), table_name="detection")
    op.drop_index(op.f("ix_detection_uuid"), table_name="detection")
    op.drop_index(op.f("ix_detection_segment_detection_id"), table_name="detection")
    op.drop_table("detection")
    op.drop_index(op.f("ix_segment_detection_video_id"), table_name="segment_detection")
    op.drop_index(op.f("ix_segment_detection_uuid"), table_name="segment_detection")
    op.drop_index(op.f("ix_segment_detection_taxonomy_id"), table_name="segment_detection")
    op.drop_index(op.f("ix_segment_detection_entity_id"), table_name="segment_detection")
    op.drop_table("segment_detection")
    op.drop_index(op.f("ix_entity_media_gallery_uuid"), table_name="entity_media_gallery")
    op.drop_index(op.f("ix_entity_media_gallery_entity_id"), table_name="entity_media_gallery")
    op.drop_table("entity_media_gallery")
    op.drop_index(op.f("ix_entity_uuid"), table_name="entity")
    op.drop_index(op.f("ix_entity_taxonomy_id"), table_name="entity")
    op.drop_table("entity")
    op.drop_index(op.f("ix_video_uuid"), table_name="video")
    op.drop_table("video")
    op.drop_index(op.f("ix_taxonomy_uuid"), table_name="taxonomy")
    op.drop_index(op.f("ix_taxonomy_taxonomy_id"), table_name="taxonomy")
    op.drop_table("taxonomy")
    # ### end Alembic commands ###
